# Generated by Django 4.1.7 on 2023-02-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_job',
            name='salary',
            field=models.IntegerField(default=True, verbose_name='Зарплата'),
        ),
    ]
