# Generated by Django 4.1.7 on 2023-02-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about_job_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_job',
            name='photo',
        ),
    ]
