# Generated by Django 4.1.7 on 2023-02-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_about_job_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_job',
            name='photo',
            field=models.ImageField(default=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
