# Generated by Django 4.1.7 on 2023-02-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_about_job_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_job',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
