# Generated by Django 4.1.7 on 2023-02-21 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_employee_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='experience',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
