# Generated by Django 4.1.7 on 2023-02-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_workexperience_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='company_name',
            field=models.CharField(default=True, max_length=255, verbose_name='Название компании'),
        ),
    ]
