# Generated by Django 4.1.7 on 2023-02-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_employer_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Название компании'),
        ),
    ]
