# Generated by Django 4.1.7 on 2023-02-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_employer_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='passwod',
            field=models.CharField(default=False, max_length=255, verbose_name='pasword'),
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(default=False, max_length=255, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='employer',
            name='passwod',
            field=models.CharField(default=False, max_length=255, verbose_name='pasword'),
        ),
        migrations.AddField(
            model_name='employer',
            name='username',
            field=models.CharField(default=False, max_length=255, verbose_name='username'),
        ),
    ]
