# Generated by Django 4.1.7 on 2023-02-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_employee_passwod_employee_username_employer_passwod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='passwod',
            field=models.CharField(max_length=255, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=255, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='passwod',
            field=models.CharField(max_length=255, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='username',
            field=models.CharField(max_length=255, verbose_name='username'),
        ),
    ]
